# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Example2 < Formula
  desc "Example for Golang Training"
  homepage "https://github.com/golang-training-examples/example2"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/golang-training-examples/example2/releases/download/v0.3.0/example2_v0.3.0_darwin_arm64.tar.gz"
      sha256 "6d8622e4652b7872933b42bf72716bd7036f97b20fa61142b2a5187c97363df6"

      def install
        bin.install "example2"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/golang-training-examples/example2/releases/download/v0.3.0/example2_v0.3.0_darwin_amd64.tar.gz"
      sha256 "991d0d43ba3d9297ccb9c7caf0b3a892a60f434549d2b7b927874387cef34518"

      def install
        bin.install "example2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/golang-training-examples/example2/releases/download/v0.3.0/example2_v0.3.0_linux_amd64.tar.gz"
      sha256 "5f22749498be4ba077e26f276d79a1f46ceb7b67adfa36455fd1e6e7c3c2331b"

      def install
        bin.install "example2"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/golang-training-examples/example2/releases/download/v0.3.0/example2_v0.3.0_linux_arm64.tar.gz"
      sha256 "570beaa19f48a8fbb1e0a5c0fd372832a6cfa7e504e9368f474db0f3d150c4bf"

      def install
        bin.install "example2"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/golang-training-examples/example2
    EOS
  end

  test do
    system "#{bin}/example2"
  end
end
