# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Example1 < Formula
  desc "Example for Golang Training"
  homepage "https://github.com/golang-training-examples/example1"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/golang-training-examples/example1/releases/download/v0.6.0/example1_v0.6.0_darwin_arm64.tar.gz"
      sha256 "70537b555b66fd35653dbc3a714e5542cf08a2bf2bc544100ae552ed5ec8d0d6"

      def install
        bin.install "example1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/golang-training-examples/example1/releases/download/v0.6.0/example1_v0.6.0_darwin_amd64.tar.gz"
      sha256 "a97712f4ded7ee80ca124ade5f8e48cdda5c2953d0bec0ca8c0b4df9785880ac"

      def install
        bin.install "example1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/golang-training-examples/example1/releases/download/v0.6.0/example1_v0.6.0_linux_arm64.tar.gz"
      sha256 "661f85ffc59decf30f02435145d455089bf460de9be8518eb2b7a0dc6d870b11"

      def install
        bin.install "example1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/golang-training-examples/example1/releases/download/v0.6.0/example1_v0.6.0_linux_amd64.tar.gz"
      sha256 "0456bae1a862506430f309dbb756d8bb3f38dbae52163fdb0960084d84f1909d"

      def install
        bin.install "example1"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/golang-training-examples/example1
    EOS
  end

  test do
    system "#{bin}/example1"
  end
end
