# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Example1 < Formula
  desc "Example for Golang Training"
  homepage "https://github.com/golang-training-examples/example1"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/golang-training-examples/example1/releases/download/v0.2.0/example1_v0.2.0_darwin_arm64.tar.gz"
      sha256 "e138c26511c24bc70bfd2b2fddc911264430c3d62604e84c344339361dbf61a7"

      def install
        bin.install "example1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/golang-training-examples/example1/releases/download/v0.2.0/example1_v0.2.0_darwin_amd64.tar.gz"
      sha256 "2284fe6b95ea2597eef92b36ba4e28bdc4e17565bc883feecb6d65cb3cadf17a"

      def install
        bin.install "example1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/golang-training-examples/example1/releases/download/v0.2.0/example1_v0.2.0_linux_arm64.tar.gz"
      sha256 "a0f69b5ddb181470bad9e99508733a3361b0344773b915d47cc16c4b72fb937d"

      def install
        bin.install "example1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/golang-training-examples/example1/releases/download/v0.2.0/example1_v0.2.0_linux_amd64.tar.gz"
      sha256 "b99cddd2e138a4dcb3945d939ee32a2e33ba9dc6173ebea28b564703dec8b148"

      def install
        bin.install "example1"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/golang-training-examples/example1
    EOS
  end

  test do
    system "#{bin}/example1"
  end
end
