# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Example2 < Formula
  desc "Example for Golang Training"
  homepage "https://github.com/golang-training-examples/example2"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/golang-training-examples/example2/releases/download/v0.6.0/example2_v0.6.0_darwin_arm64.tar.gz"
      sha256 "92cd4d469b2adc2eb3b40ef5242a89c10431524cb70100e49e2281b4aca42c6e"

      def install
        bin.install "example2"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/golang-training-examples/example2/releases/download/v0.6.0/example2_v0.6.0_darwin_amd64.tar.gz"
      sha256 "40d6456fa28c25c6a6fc3fd23afb98c6677172ed9d471ec1c75e7162cf0b8f87"

      def install
        bin.install "example2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/golang-training-examples/example2/releases/download/v0.6.0/example2_v0.6.0_linux_arm64.tar.gz"
      sha256 "567e743b0d89270aae29296076d0c8c52c11e9c2314729198d8f9ebab4d5bb38"

      def install
        bin.install "example2"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/golang-training-examples/example2/releases/download/v0.6.0/example2_v0.6.0_linux_amd64.tar.gz"
      sha256 "81f3de8cb680cb8cb8e58ccb66039d1eea0acb9a2f70ed3f04fb1cd267d7a851"

      def install
        bin.install "example2"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/golang-training-examples/example2
    EOS
  end

  test do
    system "#{bin}/example2"
  end
end
