# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Example2 < Formula
  desc "Example for Golang Training"
  homepage "https://github.com/golang-training-examples/example2"
  version "0.8.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/golang-training-examples/example2/releases/download/v0.8.0/example2_v0.8.0_darwin_arm64.tar.gz"
      sha256 "3802d98e50f57a32460c4320a58101cfdd535e33bba04f2784a674294b04dd1e"

      def install
        bin.install "example2"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/golang-training-examples/example2/releases/download/v0.8.0/example2_v0.8.0_darwin_amd64.tar.gz"
      sha256 "0fef783dad83d7cd79ec92621db4ddf0006ce430e8bdcdab2e548aad146d566a"

      def install
        bin.install "example2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/golang-training-examples/example2/releases/download/v0.8.0/example2_v0.8.0_linux_arm64.tar.gz"
      sha256 "893ecc405111963381c9a82b784bbbaf47cb8faea95added52d324fca2c8aba0"

      def install
        bin.install "example2"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/golang-training-examples/example2/releases/download/v0.8.0/example2_v0.8.0_linux_amd64.tar.gz"
      sha256 "930b6eb9f6f51fefc1e7b0d35b7a7f5ef8b131fbc5b356638bd2ab12473e0263"

      def install
        bin.install "example2"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/golang-training-examples/example2
    EOS
  end

  test do
    system "#{bin}/example2"
  end
end
