# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelloWorldCli < Formula
  desc "Hello World CLI"
  homepage "https://github.com/ondrejsika/hello-world-cli"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ondrejsika/hello-world-cli/releases/download/v0.1.1/hello-world-cli_v0.1.1_darwin_arm64.tar.gz"
      sha256 "f509f5ac2303042b009492586badee23544384e83e76bee10edc5834c83076f4"

      def install
        bin.install "hello-world-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/hello-world-cli/releases/download/v0.1.1/hello-world-cli_v0.1.1_darwin_amd64.tar.gz"
      sha256 "f3cfd24411721badea600be2feea663cb398fce8930bff16c9f1eaf2a889fef9"

      def install
        bin.install "hello-world-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ondrejsika/hello-world-cli/releases/download/v0.1.1/hello-world-cli_v0.1.1_linux_arm64.tar.gz"
      sha256 "1edcc401935e229b2a9281ff3150bb70c69340fede29f3033a7ff00fc2e2f38b"

      def install
        bin.install "hello-world-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/hello-world-cli/releases/download/v0.1.1/hello-world-cli_v0.1.1_linux_amd64.tar.gz"
      sha256 "c7d661ae3cfeb85ef816268c957bbe9a09f63e900dac58e7b532ee565aabfbec"

      def install
        bin.install "hello-world-cli"
      end
    end
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/ondrejsika/hello-world-cli
  EOS
  end

  test do
    system "#{bin}/hello-world-cli"
  end
end
