# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slu < Formula
  desc "Hello World CLI"
  homepage "https://github.com/ondrejsika/hello-world-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/hello-world-cli/releases/download/v0.1.0/hello-world-cli_v0.1.0_darwin_amd64.tar.gz"
      sha256 "c872130915b140c97284c96953ee9dd8dfbf6517f63dfd213096fa4d8ca8a47e"

      def install
        bin.install "hello-world-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ondrejsika/hello-world-cli/releases/download/v0.1.0/hello-world-cli_v0.1.0_darwin_arm64.tar.gz"
      sha256 "c2e3b3460b54ebe7898d93cf3363f176e5748493701809b7797b13f96911dd9a"

      def install
        bin.install "hello-world-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/hello-world-cli/releases/download/v0.1.0/hello-world-cli_v0.1.0_linux_amd64.tar.gz"
      sha256 "dbfc5154ffafc6d27a489b01e7cea2d5819796b3c54c3b891b9192336ecb60a7"

      def install
        bin.install "hello-world-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ondrejsika/hello-world-cli/releases/download/v0.1.0/hello-world-cli_v0.1.0_linux_arm64.tar.gz"
      sha256 "f04b3edd32638a7163f7a5672556fe70715a3e851db84e554be055341e4daa94"

      def install
        bin.install "hello-world-cli"
      end
    end
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/ondrejsika/hello-world-cli
  EOS
  end

  test do
    system "#{bin}/hello-world-cli"
  end
end
